### ISSUE TITLE
nGrinder 설치 및 사용 

### ISSUE THREAD

**Issue by ber01** [f-lab-edu/lo-gak-gye#39]
## 목표

- 퍼포먼스/스트레스 테스팅 툴인 nGrinder를 설치 및 사용한다.

**Comment by ber01** [comment]
## [nGrinder](https://github.com/naver/ngrinder)

리드미를 번역해 보면 아래와 같다.

스크립트 생성, 테스트 실행, 모니터링 및 결과 보고서 생성을 동시에 실행할 수 있는 스트레스 테스트 플랫폼

두 가지 주요 구성 요소로 이루어져 있다.

nGrinder 컨트롤러

- 성능 테스터가 테스트 스크립트를 생성하고 테스트 실행을 구성할 수 있는 웹 애플리케이션

nGrinder 에이전트

- 부하를 생성하는 가상 사용자 생성기

**Comment by ber01** [comment]
## nGrinder 컨트롤러 다운로드

- [ngrinder-3.5.8](https://github.com/naver/ngrinder/releases/tag/ngrinder-3.5.8-20221230)

<img width="1238" alt="스크린샷 2024-02-02 오전 9 18 47" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/a729aaa4-e14f-4806-b66b-8cbf1169d782">

**Comment by ber01** [comment]
## 컨트롤러 실행

```
java -jar ngrinder-controller-3.5.8.war --port=8300
```

## 오류 발생

<img width="1172" alt="image" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/3977a0a8-b12f-4530-8dca-6ce57cfc5f2b">

## 해결 방법

```
java -Djava.io.tmpdir=/Users/minkh/Desktop/nGrinder -jar ngrinder-controller-3.5.8.war --port=8300
```

- [nGrinder 성능 테스트 도중 만난 에러들](https://velog.io/@bagt/nGrinder-%EC%84%B1%EB%8A%A5-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EB%8F%84%EC%A4%91-%EB%A7%8C%EB%82%9C-%EC%97%90%EB%9F%AC%EB%93%A4)

## 컨트롤러 접속

- admin/admin 으로 접속 가능

<img width="1455" alt="image" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/769770af-6204-41ff-8127-954d02cc040b">

<img width="1455" alt="image" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/8e78bfc6-2cf2-4008-8f38-18fff8a92914">

**Comment by ber01** [comment]
## 에이전트 설치

<img width="1455" alt="스크린샷 2024-02-02 오전 9 38 59" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/e57f79c2-d383-4550-a079-ea650d53b235">

## 압축 해제

```
tar -xvf ngrinder-agent-3.5.8-localhost.tar
```

```
cd ngrinder-agent
```

## 에이전트 실행

```
./run_agent.sh
```

<img width="878" alt="image" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/7fa07c3d-4704-4769-ac33-19c4bff7f1b4">

## 에이전트 관리

<img width="1455" alt="스크린샷 2024-02-02 오전 9 43 04" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/c668b65e-50b0-4f18-9f10-e032ef9bbdd9">

<img width="1455" alt="스크린샷 2024-02-02 오전 9 44 07" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/ef9f7b47-cb52-449b-86e2-4e4f517f8359">

**Comment by ber01** [comment]
## 스크립트 생성

<img width="1558" alt="스크린샷 2024-02-02 오전 9 50 54" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/9ef904d2-e5af-4f9b-9894-bb7e2f89693e">

`GET /accounts/{accountId}` 테스트를 하기 위한 스크립트를 생성한다.

<img width="1514" alt="스크린샷 2024-02-02 오전 9 56 46" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/d9ad48c1-8439-45bb-9bed-42ed1fad48b6">

만들기를 누르면 `Groovy`로 자동으로 생성된다.

<img width="1558" alt="스크린샷 2024-02-02 오전 9 57 44" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/b396f8d0-6173-4c82-b613-4fdac1618c7f">

검증을 눌렀더니 오류가 나타난다.

<img width="1558" alt="스크린샷 2024-02-02 오전 10 16 30" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/7b26f004-3535-47b1-8f2e-d1d0b79ad17c">

```
net.grinder.engine.common.EngineException: Error while initialize test runner
	at net.grinder.scriptengine.groovy.GroovyScriptEngine.<init>(GroovyScriptEngine.java:71)
	at net.grinder.scriptengine.groovy.GroovyScriptEngineService.createScriptEngine(GroovyScriptEngineService.java:87)
	at net.grinder.engine.process.ScriptEngineContainer.getScriptEngine(ScriptEngineContainer.java:105)
	at net.grinder.engine.process.GrinderProcess.run(GrinderProcess.java:345)
	at net.grinder.engine.process.WorkerProcessEntryPoint.run(WorkerProcessEntryPoint.java:87)
	at net.grinder.engine.process.WorkerProcessEntryPoint.main(WorkerProcessEntryPoint.java:60)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Unsupported class file major version 61

java.lang.IllegalArgumentException: Unsupported class file major version 61
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:57)
	at org.codehaus.groovy.ast.decompiled.Annotations.createAnnotationNode(Annotations.java:40)
	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.addAnnotations(DecompiledClassNode.java:257)
```

## Unsupported class file major version 61

Gradle과 Java 버전이 맞지 않아서 생기는 에러

JDK를 11로 낮춘다.

```
export JAVA_HOME=/Users/minkh/Library/Java/JavaVirtualMachines/corretto-11.0.21/Contents/Home
export PATH=$JAVA_HOME/bin:$PATH
```

nGrinder 컨트롤러 재시작

```
java -Djava.io.tmpdir=/Users/minkh/Desktop/nGrinder -jar ngrinder-controller-3.5.8.war --port=8300
```

## 스크립트 검증

성공한다.

![image](https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/ea365f6c-d5ad-431b-862a-90f338362792)

실제 서버로도 요청이 온다.

<img width="1214" alt="스크린샷 2024-02-02 오전 10 33 24" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/0737be8c-6239-4f43-ad99-baf9f22a56a1">

**Comment by ber01** [comment]
## 성능 테스트

<img width="1558" alt="스크린샷 2024-02-02 오전 10 36 26" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/46288382-a11e-44a8-bdeb-48d6c2e16656">

50명의 가상 사용자의 `GET /account/{accountId}` 테스트 생성

- 스크립트 선택 및 저장 후 시작

<img width="1558" alt="image" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/2ff6a03c-5c72-481d-b336-e8fc3e455f1e">

## 결과

오류가 나타났다.

<img width="1558" alt="스크린샷 2024-02-02 오전 10 54 11" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/24fae23d-2097-4964-9d4c-fa693fe65e4d">

```
Distribution files are being prepared.
Distribution files are prepared.
Console is being prepared.
Console is started on port 12003
1 agents are starting.
1 agents are ready.
All necessary files are being distributed.
All necessary files are distributed.
The test is ready to start.
The test is started.
Script error

Stopped by error
2024-02-02 10:53:43
```

로그를 확인해 보니, 여기도 버전이 문제다.

임시로 11로 바꾸지 말고 전체를 11로 바꿔야겠다.

**Comment by ber01** [comment]
## 성능 테스트 결과

<img width="1558" alt="image" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/bef7ae3c-0571-4a88-a490-fcd2e6ff5ee1">

- 유저(User): 테스트에 참여한 가상 사용자의 수가 50명
- TPS (Transactions Per Second): 초당 처리량, 테스트 동안 평균 63.7건의 트랜잭션이 처리
- 최고 TPS: 테스트 기간 중 가장 높았던 초당 트랜잭션 수는 180.0건
- 평균 응답시간(Average Response Time): 트랜잭션의 평균 응답 시간은 534.51(ms)
- 총 실행 테스트(Total Test Runs): 총 3,707회 테스트 실행
- 성공한 테스트(Successful Tests): 성공적으로 완료된 테스트 수 3,707회
- 에러(Errors): 테스트 중 에러가 발생 건수 0건
- 테스트 시간(Test Duration): 테스트 총 1분 수행

이건 서버가 두 대일 때의 처리량이다. 한 대 일때는 어떨까?

**Comment by ber01** [comment]
## 성능 테스트 결과(서버 1대)

<img width="1558" alt="image" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/d6dfb0b5-a6ef-4e88-ba88-b3df374961ad">


항목 | 첫 번째 테스트 결과(서버 2대) | 두 번째 테스트 결과 (서버 1대)
-- | -- | --
가상 사용자 (VUser) | 50명 | 50명
평균 TPS | 63.7건 | 65.4건
최고 TPS | 180.0건 | 114.0건
평균 응답 시간 | 534.51ms | 599.99ms
총 실행 테스트 | 3,707회 | 3,674회
성공한 테스트 | 3,707회 | 3,674회
에러 | 0건 | 0건
테스트 시간 | 1분 | 1분 1초

서버가 2대일 때 처리량이 더 높다고 볼 수 있다.

**Comment by ber01** [comment]
## APM 확인

계정조회는 데이터베이스와 연관되어 있다. `HikariCP Statistics`를 확인해 본다.

Active 10개에, Pending 28개 까지 올라가있다.

실제 운영 환경일 경우 커넥션 풀의 크기를 늘려주면 응답 속도가 조금 더 개선될 것으로 예상된다.

이러한 부분은 APM 환경을 구성하지 않으면 몰랐을 것이다.

<img width="1488" alt="스크린샷 2024-02-02 오전 11 41 46" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/72b27974-c1a3-4553-9b40-4ffc0983fe82">


## [참고] 커넥션 풀 크기 조정 설정

```properties
spring.datasource.hikari.maximum-pool-size=30
```

**Comment by ber01** [comment]
## 메인 로직 부하 테스트

조건은 똑같이 유저 50명, 쓰레드 50개, 1분

- `POST /engravings/calc`

<img width="1558" alt="스크린샷 2024-02-02 오후 12 07 53" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/1d226fd6-b3b3-4936-82cc-631bf30a56b7">

계산 로직이 조금 있다 보니 평균 응답시간이 늦어지기는 한다.

근데, 평균 응답시간이 갑자기 튀는 구간이 있다.

<img width="983" alt="스크린샷 2024-02-02 오후 12 11 34" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/f186bb36-1fcd-4c3b-8433-6012705b4c47">

가끔 올라가는 구간은 데이터베이스 커넥션 반납을 기다리는 것 같고

마지막에 한번에 확 튀는 구간은 APM 모니터링을 해보니까 중간에 끊긴 기록이 있다.

<img width="1248" alt="스크린샷 2024-02-02 오후 12 12 53" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/118ff4b4-1315-4a55-ad43-6963eb1b8de7">

**Comment by ber01** [comment]
## 메인 로직 부하 테스트 - 2

쓰레드 10개, 1분

- `POST /engravings/calc`

<img width="1558" alt="스크린샷 2024-02-02 오후 12 16 57" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/0d737fc6-3c1a-49a8-8a34-5a054e9ee926">

특정 구간에서 갑자기 병목 현상이 보인다.

<img width="1558" alt="스크린샷 2024-02-02 오후 12 17 04" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/5f87de5e-4c1e-4d2e-a61a-bb2d3eff76ad">

APM 툴을 봤을 때는 별 문제는 없어 보인다. 뭐가 문제일까

## 메인 로직 부하 테스트 - 3

쓰레드 5개, 30초

- `POST /engravings/calc`

<img width="1558" alt="스크린샷 2024-02-02 오후 12 30 00" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/b48d02b2-7e5b-4b84-b545-730a0059f4eb">

안정적인 지표를 보인다.

<img width="1558" alt="스크린샷 2024-02-02 오후 12 30 15" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/9338ec41-6f20-4f68-92dd-fd0be0bd29f5">

개인적으로는 데이터베이스 커넥션 문제가 맞는 것 같은데, 지표 수집을 1초마다 하는 건 아니니까 누락이 된 거 같은 느낌이다.

**Comment by ber01** [comment]
## 커넥션 풀 사이즈 조정

30 개로 맞춰본다.

```
spring.datasource.hikari.maximum-pool-size=30
```

<img width="325" alt="스크린샷 2024-02-03 오전 4 52 17" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/e9eaebf7-4519-4d9c-b885-d95c21187752">

## 메인 로직 부하 테스트 - 4

- 시간 : 1분
- 쓰레드 : 10개
- 커넥션 풀 사이즈 : 30개
- 엔드포인트 : `POST /engravings/calc`

평균 테스트 시간이 조금 덜 튀긴 한다.

<img width="1624" alt="스크린샷 2024-02-03 오전 4 57 39" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/6e0ca78b-d8f2-47c4-b5f2-59478f233b1f">

<img width="1624" alt="스크린샷 2024-02-03 오전 4 57 48" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/22ad65c9-e2e1-4369-965d-2151007f9cac">

**Comment by ber01** [comment]
## 계정 조회 테스트

쓰레드 50개일 때, Active 10개에, Pending 28개 까지 올라갔던 계정 테스트를 다시 해본다.

### 쓰레드 50개, 1분, 커넥션 풀 사이즈 30개

<img width="1624" alt="커넥션풀 30" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/9dacee69-06b7-479c-9563-f8ba45b3627e">

### 쓰레드 50개, 1분, 커넥션풀 10개

<img width="1624" alt="커넥션풀10" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/a0d34fbd-5853-41c2-a1e6-078ce35fb6ee">

### 결과 비교

구성 | Vuser | TPS | 최고 TPS | 평균 응답 시간(ms) | 최소 응답 시간 | 성공한 테스트 | 에러 | 테스트 시간
-- | -- | -- | -- | -- | -- | -- | -- | --
커넥션풀 10개 | 50 | 63.7 | 188.0 | 534.51 | 3707 | 3707 | 0 | 00:01:00
커넥션풀 30개 | 50 | 67.8 | 205.5 | 491.34 | 3806 | 3806 | 0 | 00:01:00

- TPS 증가 : 63.7 → 67.8
- 최고 TPS 증가 : 188.0 → 205.5 
- 평균 응답 시간 감소 : 534.51 → 491.34

확실히 데이터베이스 커넥션을 늘리니 TPS(초당 트랜잭션 수)가 늘어나고 응답 시간이 감소했다.

= 처리 성능이 빨라지고, 더 빠른 응답을 할 수 있게 됐다.

<img width="289" alt="스크린샷 2024-02-03 오전 5 14 23" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/2ded61f8-3104-4196-94b4-fbed6fa4ed40">

APM 을 살펴보니, Pending도 1개이다.

## 의문점

상세 보고서의 평균 테스트 시간을 확인해 보면 병목 지점이 있다.

50초에 발생한 이 병목은 왜 생긴걸까?

<img width="1624" alt="스크린샷 2024-02-03 오전 5 17 36" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/d86e84c4-6506-4b2d-aaf9-f339210771e6">

**Comment by ber01** [comment]
## CPU 사용량 체크

- 계정 조회 테스트, 쓰레드 10개, 커넥션 풀 사이즈 30

### TPS 그래프

<img width="1223" alt="스크린샷 2024-02-04 오전 11 08 33" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/c6ded8f1-3276-419c-8455-e0cd3fa9a50a">

### 평균 테스트 시간

<img width="983" alt="스크린샷 2024-02-04 오전 11 09 12" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/735c1035-6035-4a9e-bc55-4605b9588d5e">

### CPU 사용량

1분간의 평균 테스트 시간을 보았을 때, 48초에서 병목이 발생한다.

CPU 사용량을 살펴보면 `System` 97.6% 까지 증가했다.

그렇다면, 어떠한 테스트와 모니터링을 진행하여 내 서버가 동시에 몇 명의 요청을 처리하는 지 알 수 있을까?

<img width="752" alt="스크린샷 2024-02-04 오전 11 10 07" src="https://github.com/f-lab-edu/lo-gak-gye/assets/28918801/3bd32693-4010-4aaa-919e-09b7adc47b82">
